project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - RJC-Synthetic-Control-Evaluation.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    smooth-scroll: true
    toc: true
    